### ISSUE TITLE
UX: Richer Recipe Catalog

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop-extension-ai-lab#1299]
### Epic domain

This issue is dedicated for the creations of the mockups for building a richer recipe catalog.

## Expand the technologies

Each recipes are focused on a particular use case, example "creating a chatbot" or "building a text summarizer". 
Those recipes could, be build with different tools, frameworks and languages. 

- As a user, I should be able to define the technologies (tools, frameworks and languages) I want to filter the recipes, so I can see only those who are interesting to me.
- As a user, I should be able to see the technologies used by the recipes while I'm browsing the catalog of recipes
- As an end-user, I want to be able to search for recipes that use a specific combination of programming languages and technologies so that I can find complex workflows or integrations.

## Hardware specific

A recipe, might be optimized for a particular hardware architecture. We should be surfacing this to the end-user.
Example: a sample is optimized to be running on Intel infrastructure and as such, use specific Intel components (openvino). 

- As an end-user, I want to know which specific hardware components a recipe uses so that I can ensure compatibility with my existing infrastructure.
- As an end-user, I want to be able to run a recipe optimized for my specific hardware architecture without having to worry about compatibility issues so that I can focus on using the recipe effectively. 
- As an end-user, I want to be able to filter recipes in the catalog by hardware architecture so that I can find recipes optimized for my specific setup.

## Application Patterns

There are more and more application patterns that are being worked on by the community. Those could be related to pre-processing, post-processing, rag, guardrails. 
We should also provide categories of recipes that are covering different application patterns.

## Contributions

We would like to include a way in the recipe catalog to indicate to the end-users and the community, where they can find the catalog, how they can expand it with their own catalog and eventually contribute to the upstream catalog.

**Comment by ekidneyrh** [comment]
Love the detail that is in this ticket! I have a few comments: 

Just wanted to add what the Recipe Catalog looks like at the moment for context.

![Screenshot from 2024-07-24 12-23-40](https://github.com/user-attachments/assets/7daa6105-6916-4607-8436-6b8c6d5227c9)

> As a user, I should be able to define the technologies (tools, frameworks and languages) I want to filter the recipes, so I can see only those who are interesting to me.

How would we filter them? Include a filter option. Preset filters or type search? Maybe both?

> As a user, I should be able to see the technologies used by the recipes while I'm browsing the catalog of recipes

Add tags to the cards - dont have to be visible on the cards themselves, maybe encoded so that when the technology is search for the relevant recipes appear. 

> As an end-user, I want to be able to search for recipes that use a specific combination of programming languages and technologies so that I can find complex workflows or integrations.

Same as previous point.

> As an end-user, I want to know which specific hardware components a recipe uses so that I can ensure compatibility with my existing infrastructure.
> As an end-user, I want to be able to run a recipe optimized for my specific hardware architecture without having to worry about compatibility issues so that I can focus on using the recipe effectively.
> As an end-user, I want to be able to filter recipes in the catalog by hardware architecture so that I can find recipes optimized for my specific setup.

For the hardware points, I think again having tags in the metadata so that when searched for the relevant card get filtered. I’m not sure if this is something we would want displayed in the card? 

I think from this information we may want to look at adding a more advanced filter interface. Something like this but adapted for our needs:

![image](https://github.com/user-attachments/assets/a07d8352-dd3a-4cb7-a895-c89bfadbf387)

At least here we could have options for hardware, tools, frameworks, languages.

At the moment, I only see a handful of options in the recipes in the recipe catalog, so having a lot of filter options might be inconsequential at the moment, but I see you mentioned that there is more being worked on, which is good. Do you think by the time this is deployed that there will be a significant amount of recipes in the catalog that would require filtering? 

Next steps / decisions we need for this I think should be:

- Determine what tags we want to filter by
  - Add the metadata tags to the cards
  - Do we want them displayed on the cards?
- Explore a filter menu UI 
  - What do we want it to look like?

Let me know what you think. I can open any relevant tickets.

**Comment by ekidneyrh** [comment]
@slemeur pinging for above ^

**Comment by slemeur** [comment]
> How would we filter them? Include a filter option. Preset filters or type search? Maybe both?

I think we should have an header at the top of the list that allows to select/configure the desired "Environments". 

> Add tags to the cards - dont have to be visible on the cards themselves, maybe encoded so that when the technology is search for the relevant recipes appear.

Yeah, there might be some tags that we would like to show, and some that we would like to hide. Ideally, the user would be able to select the categories of tags to be displayed in the list, but that would be a nice to have.

> I think from this information we may want to look at adding a more advanced filter interface. Something like this but adapted for our needs

Yes something like this would be working fine.

> Determine what tags we want to filter by
> - Add the metadata tags to the cards
> - Do we want them displayed on the cards?

I'm creating a mini spec for this.

> Explore a filter menu UI
> - What do we want it to look like?

Yes, I think we need to explore that.

**Comment by MariaLeonova** [comment]
@slemeur @ekidneyrh this ticket seems to have an epic scope to me, as it covers a range of things. Namely:
- adding filter + search functionality 
- adding tags to cards and cards metadata
- finding ways to educate users about the catalog

Would it be feasible to have separate issues for them?

**Comment by MariaLeonova** [comment]
Created https://github.com/containers/podman-desktop-extension-ai-lab/issues/1628 for tags and metadata

**Comment by MariaLeonova** [comment]
Created https://github.com/containers/podman-desktop-extension-ai-lab/issues/1629 for contributions.

**Comment by slemeur** [comment]
Closing as splitted into multiple sub-issues
