### ISSUE TITLE
GPU support for recipes

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop-extension-ai-lab#1467]
### Is your enhancement related to a problem? Please describe

Starting recipes should handle GPU enablement. GPU environnment is configured through gpu-env field on the model-service container

### Describe the solution you'd like

When starting the model service, we should select the proper container and start it with the proper configuration.

The algorithm to select the proper container shoul be:
- count the number of accepted conditions (arch and gpu-env)
- take the container that has the most accepted conditions

**Comment by axel7083** [comment]
The GPU support should for recipes should not copy past code from the InferenceManager or the InferenceProviders, instead it should use it. Here are some thought about a possible solution:

## Add the Inference Server Container to the pod of the recipe

When creating a recipe, we are creating a Pod. The ApplicationManager should not be responsible of creating the container of the model service, instead it should create an InferenceServer using the `createInferenceServer` 

https://github.com/containers/podman-desktop-extension-ai-lab/blob/8563129531a0850365f724c5645abbb3c9e30ecf/packages/backend/src/managers/inference/inferenceManager.ts#L168

However, this would not allow in the current state to create the inference server container inside the pod, so a new optional property should probably be added to the InferenceServerConfig[^1], a property named `podId`.

The different InferenceProviders (LLamaCppPython[^2]...) will need to add the `pod` property to the `ContainerCreateOptions`.
 
## Add the devices/config to the pod configuration

If you simply add the container of the inference server to the pod of the recipe, **it will not be able to access the mounted devices** because the pod did not declare them.

Currently we do not seems to have the pod devices configurable in the extension-api[^3]. Some change in the API may be required, see the podman documentation for that [PodCreateLibpod](https://docs.podman.io/en/latest/_static/api.html#tag/pods/operation/PodCreateLibpod). 


[^1]: https://github.com/containers/podman-desktop-extension-ai-lab/blob/9ded94378f9cefe00130aa52212b0136f5e06180/packages/shared/src/models/InferenceServerConfig.ts#L22
[^2]: https://github.com/containers/podman-desktop-extension-ai-lab/blob/b21d83ffcd864565b975c28eef3c3eef5cc12081/packages/backend/src/workers/provider/LlamaCppPython.ts
[^3]: https://github.com/containers/podman-desktop/blob/ffe418e95298e518ec3283246c7529cdba5c97ef/packages/extension-api/src/extension-api.d.ts#L376

**Comment by jeffmaury** [comment]
Looks over complicated to me as moving a container to a pod will stop it (the inference server).

So I think there are 2 solutions:

1. build and start the proper mode server container
2. start or reuse the inference server

The 2 has to pro that it does not require the recipes to be updated

**Comment by lstocchi** [comment]
> 2. start or reuse the inference server

you mean calling the inference server which is external to the pod? So having a pod with 1 container (the recipe)?

**Comment by jeffmaury** [comment]
> > 2. start or reuse the inference server
> 
> you mean calling the inference server which is external to the pod? So having a pod with 1 container (the recipe)?

Yes so that starting a recipe will start a pod with a single container (the app ui) for most of the recipes and start or connect to the inference server

**Comment by axel7083** [comment]
> Looks over complicated to me as moving a container to a pod will stop it (the inference server).

We are not creating the container then adding it to the pod, we are creating the container inside the pod, to do so as I explained we need to pass the `pod` property to the CreateContainerOptions that calls the inference provider.

> you mean calling the inference server which is external to the pod? So having a pod with 1 container (the recipe)?

Love this idea ! However, we have to know a few things, first the pod is in its own network, so it cannot directly call the inference server.

Since https://github.com/containers/podman-desktop/pull/7431 and https://github.com/containers/podman-desktop/pull/7805 I added the networks argument in the podman-desktop api so we can created a dedicated network for AI Lab, where the pod and the inference server will be added, so they will be able to communicates.

We might need to discuss this in a dedicated call as this is a large change in the architecture and could have some implications

**Comment by lstocchi** [comment]
Investigated a bit. It looks like that the podman pod has visibility over the host space. 
So, if i have to call a service running on the HOST outside the pod from the container running within it, i could use `host_ip:port`.
Docker introduced a special DNS name (`host.containers.internal`) to simplify access to the host machine from within containers and it seems that podman also supports it.
So we could start the inference server as we do (let's say it listens to port 50100), then call it from the container within the pod by calling `host.containers.internal:50100/v1`

**Comment by axel7083** [comment]
> Investigated a bit. It looks like that the podman pod has visibility over the host space. So, if i have to call a service running on the HOST outside the pod from the container running within it, i could use `host_ip:port`. Docker introduced a special DNS name (`host.containers.internal`) to simplify access to the host machine from within containers and it seems that podman also supports it. So we could start the inference server as we do (let's say it listens to port 50100), then call it from the container within the pod by calling `host.containers.internal:50100/v1`

That's a good news !

**Comment by axel7083** [comment]
I have some concern about what would became the container definition defined in the `ai-lab.yaml`, IMO we should not overwrite them, as they allow the user to create their own model-service as needed, and do what they would need with the models.

First: we need the `ai-lab.yaml` to be explicit about the model-service(s) they need to work. 

Currently they define it by explicitly provide the container file to build. We know that we should be mounting the model file since they are providing `model-service: true`.

```
  containers:
    - name: llamacpp-server
      contextdir: ../../../model_servers/llamacpp_python
      containerfile: ./base/Containerfile
      model-service: true
      backend:
        - llama
      arch:
        - arm64
        - amd64
      ports:
        - 8001
      image: quay.io/ai-lab/llamacppp_python:latest
``` 

Since we want to uses the model-services from the `InferenceManager` where they provide their own image, how does the `ai-lab.yaml` define this requirements.

## What do we do if the ai-lab.yaml recipes is defining a model-service ?

### Proposal 1

We should keep the existing behaviour when the `ai-lab.yaml` define a model-service, however we could introduce a new optional `model-services` field, allowing the user to request model-service.

Here is an example of what the chat bot `ai-lab.yaml`[^1] would look like after migration:

[^1]: https://github.com/containers/ai-lab-recipes/blob/main/recipes/natural_language_processing/chatbot/ai-lab.yaml

```diff
version: v1.0
application:
  type: language
  name: ChatBot_Streamlit
  description: Chat with a model service in a web frontend.
  containers:
-    - name: llamacpp-server
-      contextdir: ../../../model_servers/llamacpp_python
-      containerfile: ./base/Containerfile
-      model-service: true
-      backend:
-        - llama
-      arch:
-        - arm64
-        - amd64
-      ports:
-        - 8001
-      image: quay.io/ai-lab/llamacppp_python:latest
    - name: streamlit-chat-app
      contextdir: app
      containerfile: Containerfile
      arch:
        - arm64
        - amd64
      ports:
        - 8501
      image: quay.io/ai-lab/chatbot:latest
+ model-services:
+    - name: LLAMA_CPP_MODEL_SERVICE
+      backend: llama-cpp
+    - name: WHISPER_CPP_MODEL_SERVICE
+      backend: whsiper-cpp
```

In this example, all containers would have the `LLAMA_CPP_MODEL_SERVICE` and `WHISPER_CPP_MODEL_SERVICE` environment variable value set to the `host:port` of the corresponding model service.

### Proposal 2

When the recipe start, user could be offer the possibility to use _custom model service_ or _do not use inference server_, like advanced option in the StartRecipe page, where the user could say: use my own containerfile to build the inference server.

**Comment by lstocchi** [comment]
I agree that there is no reason to overwrite the `ai-lab` file as we need those infos.

I don't get the env variable changes tbh. We could just check if the image used for the model service is `quay.io/ai-lab/llamacppp_python:latest` then we can use our inference server, otherwise it works as before -> CPU.

**Comment by axel7083** [comment]
> I don't get the env variable changes tbh. We could just check if the image used for the model service is `quay.io/ai-lab/llamacppp_python:latest` then we can use our inference server, otherwise it works as before -> CPU.

What the `ai-lab.yaml` would look like ?

```diff
 containers:
-    - name: llamacpp-server
-      contextdir: ../../../model_servers/llamacpp_python
-      containerfile: ./base/Containerfile
-      model-service: true
-      backend:
-        - llama
-      arch:
-        - arm64
-        - amd64
-      ports:
-        - 8001
-      image: quay.io/ai-lab/llamacppp_python:latest
+   - name: llamacpp-server
+     model-service: true
+     backend:
+        - llama
+     image: quay.io/ai-lab/llamacppp_python:latest
```

Checking for the image `quay.io/ai-lab/llamacppp_python:latest` and relacing it with the inference server dedicated image is overwritting the declaration of the ai-lab.yaml, as we are not respecting what they requires.

The change of env is here to allow multiple model services. IMO the inference server(s) should not be declared in the containers if they are not part of the pod. Since we are providing an external service, it really feed odd to have it included or somehow overwritten in the containers array.

**Comment by lstocchi** [comment]
> What the `ai-lab.yaml` would look like ?
> 
> ```diff
>  containers:
> -    - name: llamacpp-server
> -      contextdir: ../../../model_servers/llamacpp_python
> -      containerfile: ./base/Containerfile
> -      model-service: true
> -      backend:
> -        - llama
> -      arch:
> -        - arm64
> -        - amd64
> -      ports:
> -        - 8001
> -      image: quay.io/ai-lab/llamacppp_python:latest
> +   - name: llamacpp-server
> +     model-service: true
> +     backend:
> +        - llama
> +     image: quay.io/ai-lab/llamacppp_python:latest
> ```
> 

The `ai-lab.yaml` does not change as my understanding in this first iteration.

> Checking for the image `quay.io/ai-lab/llamacppp_python:latest` and relacing it with the inference server dedicated image is overwritting the declaration of the ai-lab.yaml, as we are not respecting what they requires.

In the configuration we are describing the containers needed to run the recipe. If the recipe requires a model service using llamacpp image and we have an inference server that is running with the same llamacpp image i don't see why we are not respecting the config. We still have 2 containers running with the images specified by the ai-lab config file.

> The change of env is here to allow multiple model services. IMO the inference server(s) should not be declared in the containers if they are not part of the pod. Since we are providing an external service, it really feed odd to have it included or somehow overwritten in the containers array.

I think that it really depends on how we see the content of `ai-lab.yaml`. Now we associate it with a pod bc we already have handled it like that, but the file has nothing that specify that the 2 containers has to be inside the same pod. We could just handled them as we want locally. We could also maintain the config like it is now bc it could be useful in future if we have to wrap everything before pushing a pod to a remote cluster.

**Comment by axel7083** [comment]
Closing as completed by https://github.com/containers/podman-desktop-extension-ai-lab/pull/1503
