### ISSUE TITLE
Add banner about GPU acceleration if not used/configured

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop-extension-ai-lab#1591]
### Is your enhancement related to a problem? Please describe

People who are not aware of the possibility of using GPU acceleration will not notice the capability.

### Describe the solution you'd like

If the GPU is not configured in the user's environment, we'd like to drive more attention onto how the user could experiment with it.

- The banner should be displayed at the top of all screens of Podman AI Lab
- The title should be "⚡️ **Supercharge Your AI:**  Enable GPU Acceleration and watch your LLM respond in a flash! "
- There should be one button "Enable": when clicked, it displays the instructions on how the user can enable the GPU acceleration, depending on the platform the user is using.

It should be possible to hide the banner with a button: "Don't display anymore"

We should have telemetry on the banner to know:
- how often it's been displayed
- how often the user clicked on "enable" or "don't display anymore"

**Comment by axel7083** [comment]
We may want to simply have it enabled by default next release

**Comment by axel7083** [comment]
> The banner should be displayed at the top of all screens of Podman AI Lab

I am against this idea.

> There should be one button "Enable": when clicked, it displays the instructions on how the user can enable the GPU acceleration, depending on the platform the user is using.

![image](https://github.com/user-attachments/assets/f210e6de-746f-44fc-a6e7-2c8bdd9f9d6d)

Following https://github.com/containers/podman-desktop-extension-ai-lab/pull/1717 we have a banner checking for GPU machine (libkrun).

This issue seems to be a change on this existing banner ? 

On Windows we should only display this for user with NVIDIA card and VRAM > 6G as this is probably the minimum requirements. We could redirect them to the documentation (https://podman-desktop.io/docs/podman/gpu)

**Comment by axel7083** [comment]
Knowing if a WSL has nvidia capabilities is difficult, and we would need to manually ssh inside the machine.

I opened https://github.com/containers/podman/issues/24042 to see if we could have this information from the machine.

**Comment by jeffmaury** [comment]
Having the default value switched to true is a first step but we should have the banner displayed if user changed it to false
