### ISSUE TITLE
Using an imported model mount the entire folder in the inference server

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop-extension-ai-lab#1992]
### Bug description

When user is importing a model and starting an inference server for it, the entire user's folder where the model is located is getting mounted in the container which causes performance issues or the inference server not able to start.

### Operating system

mac OS 

### Installation Method

from Podman-Desktop extension page

### Version

1.3.x

### Steps to reproduce

1. Download a model in a folder with a lot of files
2. Import it from ai lab model catalog
3. Start Inference Server

**Comment by axel7083** [comment]
This is our mountconfig

https://github.com/containers/podman-desktop-extension-ai-lab/blob/21945c5a450db57b95ada11d48f1393e09f03f2a/packages/backend/src/workers/provider/LlamaCppPython.ts#L88-L92

Historically we choose to mount the folder where the model is located because we wanted to support models in non-gguf format, which tends to be multiple files.

This should probably not apply to LlamaCppPython, as it require only the file, we should mount the file as a target, and not the folder
