### ISSUE TITLE
Design Icons for Playground Environments

### ISSUE THREAD

**Issue by nichjones1** [containers/podman-desktop-extension-ai-lab#527]
This is a design issue for the creation of the Playground Icons in AI Studio

**Comment by vrothberg** [comment]
@ekidneyrh did you find the information you were looking for?
Otherwise, @nichjones1, @slemeur or @benoitf may be able to help.

**Comment by slemeur** [comment]
We need an icon for this list in particular:
<img width="1193" alt="Screenshot 2024-04-09 at 18 59 31" src="https://github.com/containers/podman-desktop-extension-ai-lab/assets/1636769/bd01b627-1837-4c77-883a-dba445333121">

Similar to what we have for other lists in fact:
<img width="541" alt="Screenshot 2024-04-09 at 19 00 10" src="https://github.com/containers/podman-desktop-extension-ai-lab/assets/1636769/43d8ca7b-26ca-4905-917d-b9523f17937b">

**Comment by ekidneyrh** [comment]
Since playground environments are a place where engineers can play around and experiment, I think we should take a fun approach. I know this is usually done with sandbox, where it’s visualised as a shovel and bucket or a literal sandbox.  We could go this way too, as there are multiple icons illustrating this. 

![Screenshot from 2024-04-15 21-49-25](https://github.com/containers/podman-desktop-extension-ai-lab/assets/87311656/95ad91bc-7c93-46dc-b040-bd9e9fa897ec)
![Screenshot from 2024-04-15 21-48-49](https://github.com/containers/podman-desktop-extension-ai-lab/assets/87311656/7f3a0c3a-be12-4041-b7ef-74f1b2dbb4f3)
![Screenshot from 2024-04-15 21-47-42](https://github.com/containers/podman-desktop-extension-ai-lab/assets/87311656/de83bce3-2c1d-46f3-b1d8-9704b27e0991)
![Screenshot from 2024-04-15 21-47-23](https://github.com/containers/podman-desktop-extension-ai-lab/assets/87311656/c4e76363-5433-4e12-a16c-e94ffaeeafe1)


We could also go with beach toys such as a beach ball or even just a toy or a game controller if we don’t want to be too literal. 

![Screenshot from 2024-04-15 21-50-55](https://github.com/containers/podman-desktop-extension-ai-lab/assets/87311656/0a9b5e6a-9822-4c7d-9767-fa1d3dcd50a7)
![Screenshot from 2024-04-15 21-50-26](https://github.com/containers/podman-desktop-extension-ai-lab/assets/87311656/40ae875b-4f6f-4f04-96f3-cc6f41e82905)
![Screenshot from 2024-04-15 21-50-01](https://github.com/containers/podman-desktop-extension-ai-lab/assets/87311656/15a6ff75-28b2-4062-89ce-f13e0cb07275)


I can do up any thing to match the style of our other icons. 

Just to confirm, is it three different states that are used in the list like in the images and pod screens? Outline for inactive, filled green for active and then a yellow for kinda active? I must document that somewhere bc I keep forgetting.

**Comment by slemeur** [comment]
I'd go with this one which brings a bit of chemistry: 
![Screenshot from 2024-04-15 21-47-23](https://github.com/containers/podman-desktop-extension-ai-lab/assets/87311656/c4e76363-5433-4e12-a16c-e94ffaeeafe1)

**Comment by slemeur** [comment]
> Just to confirm, is it three different states that are used in the list like in the images and pod screens? Outline for inactive, filled green for active and then a yellow for kinda active? I must document that somewhere bc I keep forgetting.

Yes that's correct :) 

Thanks @ekidneyrh !

**Comment by ekidneyrh** [comment]
![rect1](https://github.com/containers/podman-desktop-extension-ai-lab/assets/87311656/80e9b296-b192-47fa-8a62-f8b896b039d0)

So the icons would look like this then? The licence on the icon is [MIT](https://gitlab.com/SUSE-UIUX/eos-icons/-/blob/master/LICENSE) so we can use it :) I just adjusted it to add a stroke box and a filled bg. I'm not 100% what format is needed but here are the SVGs coloured and just in white in case. 

here's a link to them on Gdrive: https://drive.google.com/file/d/1w07rlwDuaXMYEF16Z2S_vjI8CNCKgy_5/view?usp=sharing

and a zip:
[playground-env-svgs.zip](https://github.com/containers/podman-desktop-extension-ai-lab/files/14997364/playground-env-svgs.zip)

**Comment by ekidneyrh** [comment]
Also talking with Tuomas, and he suggested a merry-go-round, which would also be a fun idea :) 
![image](https://github.com/containers/podman-desktop-extension-ai-lab/assets/87311656/b8992ad6-f361-4d75-8692-381da720e80e)

**Comment by ekidneyrh** [comment]
Icons have been uploaded here: https://github.com/containers/podman-desktop-internal/tree/main/ai-lab/icons/playground-env-svgs also

**Comment by ekidneyrh** [comment]
> Reopening because of the linked PR

whoops apologies!

**Comment by jeffmaury** [comment]
> > Reopening because of the linked PR
> 
> whoops apologies!

NP
