### ISSUE TITLE
inconsistent UX when trying to start a recipe with a non downloaded model

### ISSUE THREAD

**Issue by feloy** [containers/podman-desktop-extension-ai-lab#757]
The user gets an error message if he tries to start a recipe with a model which is not downloaded. But not always (reasons are not clear, needs more investigation).

https://github.com/containers/podman-desktop-extension-ai-lab/assets/9973512/5ac10e93-9a56-40a5-9dbb-b0995571c958

**Comment by lstocchi** [comment]
I've been trying to replicate it without any luck. Maybe it was fixed in the meantime.
By looking at the error in the video and the code we should be fine.

The error `model is not available locally.` is raised here

https://github.com/containers/podman-desktop-extension-ai-lab/blob/7e1ef21f166d231f006d93e1f89cad61d8158dfc/packages/backend/src/utils/modelsUtils.ts#L29-L32

when the model has the file property undefined.

This function gets called in modelsManager through

https://github.com/containers/podman-desktop-extension-ai-lab/blob/7e1ef21f166d231f006d93e1f89cad61d8158dfc/packages/backend/src/managers/modelsManager.ts#L163-L165

getLocalModelPath is called within the downloadModel function which is called when starting an AI App

https://github.com/containers/podman-desktop-extension-ai-lab/blob/7e1ef21f166d231f006d93e1f89cad61d8158dfc/packages/backend/src/managers/modelsManager.ts#L350-L360

and the if clause is only true when the file prop is not undefined
https://github.com/containers/podman-desktop-extension-ai-lab/blob/7e1ef21f166d231f006d93e1f89cad61d8158dfc/packages/backend/src/managers/modelsManager.ts#L144-L147

So if we get inside the if branch and ends up calling `getLocalModelFile` it's because the file is not undefined and then the error should never be raised.

**Comment by feloy** [comment]
I think it was due to using a local catalog, similar to #814.

I cannot reproduce it with latest version. It's most probably fixed by #771
