### ISSUE TITLE
"Open in VSCode" to open the higher directory in repo 

### ISSUE THREAD

**Issue by mohan-shash** [containers/podman-desktop-extension-ai-lab#899]
During the weekly demo on Apr 15 [1], we discussed the discoverability of other AI models and make files in the repo. There was a suggestion from Dan Walsh to explore the possibility of changing the "Open in VSCode" to the higher directory in the repo which shows the other recipes/models. 

We do not know who is leading the UX efforts for Podman Desktop now, so @vrothberg could you please look at this?

[1] https://drive.google.com/open?id=1M2eKyD5pZaw0PaD6569crhBCEOzV7yHt

**Comment by vrothberg** [comment]
The current behavior is intended.  The reasoning is to only open the current recipe.  If a user navigates to another recipe in AI Lab and opens it in VSCode, they will only open the specific one.  Otherwise, they may likely get lost.  Another reason is that not all recipes in AI-Lab-Recipes are supported in AI-Lab.

Cc: @rhatdan

**Comment by slemeur** [comment]
Yeah I confirm.
